services:
  - type: web
    name: deepseek-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MODEL_NAME
        value: deepseek-r1:1.5b
      - key: PORT
        value: 8080
      - key: MAX_TOKENS
        value: 2048
    healthCheckPath: /health
    autoDeploy: true
